config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users do
    resources :ledgers
  end
  post '/verify', to: 'users#verify'

end

app/models/ledger.rb
class Ledger < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ledgers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ledgers_controller.rb
class LedgersController < ApplicationController
  skip_before_filter  :verify_authenticity_token

  def index
    @user = User.find(params[:user_id])
    @ledgers = @user.ledgers
    @ledger = Ledger.new
  end


  def create
    @user = User.where('id = ?', params[:user_id])
    @ledger = @user.first.ledgers.create(ledger_params)
    render :new
  end

  def show
    user_id = params[:user_id]
    @ledger = Ledger.find(params[:id])
    @ledgers = Ledger.where('user_id = ? AND name = ?', user_id, @ledger.name)
  end

  def destroy
    user = User.find(params[:user_id])
    user.ledgers.find(params[:id]).destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @ledger = @user.ledgers.find(params[:id])
    render partial:"edit"
  end

  def update
    # @ledgers = Ledgers.all
    @user = User.find(params[:user_id])
    @ledger = @user.ledgers.find(params[:id])

    @ledger.update_attributes(ledger_params)
    render :new
  end

private
  def ledger_params
    params.require(:ledger).permit(:user, :item, :price, :note, :payment_type, :expenditure)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.new
  end

  def new
    @user = User.new
  end

  def create
    name = params[:user][:name]
    email = params[:user][:email]
    password = params[:user][:password]
    @user = User.create(name: name, email: email, password: password)
    redirect_to user_path(id: @user.id)
  end

  def verify
    @user = User.where('email = ? AND password = ?', params[:user][:email], params[:user][:password])
    if @user != []
      redirect_to user_path(id: @user.first.id)
    else
      flash[:notice] = "Login Fail"
      redirect_to root_path, flash: { notice: "Login Fail"}
    end      
  end

  def show
    redirect_to user_ledgers_path(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ledgers_helper.rb
module LedgersHelper
  def filter_result(attr_name)
    return attr_name != "user_id" && attr_name != "created_at" && attr_name != "updated_at" && attr_name != "id"
  end

  def get_date(purchase)
    day = purchase.created_at.day
    month = purchase.created_at.month
    year = purchase.created_at.year
    "#{month}/#{day}/#{year}"
  end

  def time_ago(created_at)
    sec = Time.now - created_at
    from_time = Time.now - sec
    return time_ago_in_words(from_time)
  end

  def calc_total
    sum = 0
    @ledgers.each do |purchase|
      sum += purchase.price
    end
    return sum
  end

  def expenditure_breakdown
    total = calc_total
    chart_hash = {}
    @ledgers.each do |purchase|
      chart_hash[purchase.expenditure] = (purchase.price/total)
    end
    return chart_hash.to_a
  end

  def payment_breakdown
    total = calc_total
    chart_hash = {}
    @ledgers.each do |purchase|
      chart_hash[purchase.payment_type] = (purchase.price/total)
    end
    return chart_hash.to_a
  end

  def get_table_headers
    @headers = ["Date", "Item", "Price($)", "Note", "Payment", "Expenditure"]
  end




end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ledger App
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Signika' rel='stylesheet' type='text/css'>
    = stylesheet_link_tag 'css/application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield
    %script{:src => "http://code.jquery.com/jquery-1.11.1.min.js"}
    %script{:src => "http://code.highcharts.com/modules/exporting.js"}
    %script{:src => "http://code.highcharts.com/highcharts.js"}

app/views/ledgers/_edit.html.haml
.edit_form
  = form_for [@user, @ledger], url: {action: "update"} do |f| 

    = f.text_field :item, placeholder: "Item", class: "input-field"
    = f.text_field :price, placeholder: "Price ($)", class: "input-field"
    = f.text_field :note, placeholder: "Note", class: "input-field"
    = f.select :payment_type, ["Credit", "Cash", "Debit", "PayPal", "Venmo"]
    = f.select :expenditure, ["Food", "Transportation", "Leisure", "Housing", "Other"]

    = f.submit "Update", id: "update-btn"
%h1#hidden_info
  #{@user.id},#{@ledger.id}

app/views/ledgers/_form.html.haml
.ledger_form
  = form_for @ledger, url: user_ledgers_path(@user) do |f| 

    = f.text_field :item, placeholder: "Item", class: "input-field"
    = f.text_field :price, placeholder: "Price ($)", class: "input-field"
    = f.text_field :note, placeholder: "Note", class: "input-field"
    = f.select :payment_type, ["Credit", "Cash", "Debit", "PayPal", "Venmo"]
    = f.select :expenditure, ["Food", "Transportation", "Leisure", "Housing", "Other"]

    = f.submit "Log", id: "log-btn"

app/views/ledgers/_navbar.html.haml
.title-header
  Welcome, #{@user.name.capitalize}!
.menu#home-btn
  Home
.menu
  |
.menu#chart-btn
  Chart
.menu
  |
.menu#export-btn
  Export

app/views/ledgers/_piechart.html.haml
#container


:javascript

  var pieChart = function(){

    $(function () {
        $('#container').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: 1,//null,
                plotShadow: false,
                backgroundColor: 'rgba(255,255,255,0.8)'
            },
            title: {
                text: "#{@chart_title}"
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                        style: {
                            color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                        }
                    }
                }
            },
            series: [{
                type: 'pie',
                name: 'Expenditure Breakdown',
                data: #{"#{expenditure_breakdown}"}
            }]
        });
    });

  }

app/views/ledgers/_river.html.haml
.ledgers
  #new-btn.fa.fa-plus-square-o
  - @ledgers.reverse_each do |purchase|
    .item
      .price
        $#{purchase.price}0
      .item-header
        = link_to purchase.item, user_ledger_path(id: purchase.id), class: "purchase-link"
      .item-btns  
        #delete-btn.fa.fa-minus-square-o
        #edit-btn.fa.fa-edit
      %h2.note  
        = purchase.note
      .date
        = time_ago(purchase.created_at)

app/views/ledgers/_table.html.haml
%table{class: "ledger-table"}
  %tbody
    %tr{class: "top-row"}
    - get_table_headers
    - @headers.each do |title|
      %td#table-title
        =title
    - @ledgers.reverse.each do |purchase|
      %tr{class: "table-content"}
        %td= get_date(purchase)
        %td= purchase.item
        %td= purchase.price
        %td= purchase.note
        %td= purchase.payment_type
        %td= purchase.expenditure

app/views/ledgers/edit.html.haml
.edit_form
  = form_for @ledger, url: user_ledgers_path(@user) do |f| 

    = f.text_field :item, placeholder: "Item", class: "input-field"
    = f.text_field :price, placeholder: "Price ($)", class: "input-field"
    = f.text_field :note, placeholder: "Note", class: "input-field"
    = f.select :payment_type, ["Credit", "Cash", "Debit", "PayPal", "Venmo"]
    = f.select :expenditure, ["Food", "Transportation", "Leisure", "Housing", "Other"]

    = f.submit "Log", id: "log-btn"

app/views/ledgers/index.html.haml
.container
  .header
    = render partial: "navbar"

  .ledger-list
    = render partial: "form"

  = render partial: "river"
  
  = render partial: "table"


  / Filter for highchart to select different piecharts
  / %select{name: "city_id", id:"city_id"}
  /   %option{value:1}Lisbon
  /   %option{value:2}Madrid
  /   %option{value:12}Berlin


  / - if :filter == "Expenditure"
  /   hi
  /   - @chart_title = "Expenditure Breakdown"
  /   - @analysis = expenditure_breakdown
  / - elsif :filter == "Payment Type"
  /   = hello
  /   - @chart_title = "Payment Type"
  /   - @analysis = payment_breakdown

  = render partial: "piechart"

app/views/ledgers/new.html.haml
.item
  .price
    $#{@ledger.price}0
  .item-header
    = link_to @ledger.item, user_ledger_path(id: @ledger.id), class: "purchase-link"
  .item-btns  
    #delete-btn.fa.fa-minus-square-o
    #edit-btn.fa.fa-edit
  %h2.note  
    = @ledger.note
  .date
    = time_ago(@ledger.created_at)

app/views/ledgers/show.html.haml
/ .ledger-container
/   .header
/     .title-header
/       #{@ledgers.first.name.capitalize}
/     .menu-button
/       = link_to content_tag(:i,nil, class:"fa fa-reply"), user_ledgers_path(user_id: params[:user_id])
/   %br
/   #container{:style => "min-width: 410px; height: 300px; margin: 0 auto"}
/   = render partial: "form"

/   %table{class: "table_format"}
/     %tr
/       %td{class: "top_row"}
/         Date
/       - @ledgers.first.attributes.each do |attr_name, value|
/         %td{class: "top_row"}
/           - if value != nil
/             - if filter_result(attr_name)
/               = attr_name.capitalize
/       - @ledgers.each do |ledger|
/         %tr
/           %td
/             = get_date(ledger)
/           - ledger.attributes.each do |attr_name, value|
/             %td
/               - if value != nil
/                 - if filter_result(attr_name)
/                   = value 

app/views/users/index.html.haml
.container
  = form_for @user, url: {action: "verify"} do |f| 
    = f.text_field :email, placeholder: 'Email', class: "input-field", required: true
    = f.password_field :password, placeholder: 'Password', class: "input-field", required: true
    = f.submit "Login", class: "btn"

    = link_to "Sign Up", new_user_path, id: "signup"

%br
%br

.flash_msg
  - flash.each do |name, msg|
    = msg

app/views/users/new.html.haml
.container
  = form_for @user do |f| 

    = f.text_field :name, placeholder: 'Name', class: "input-field", required: true

    = f.text_field :email, placeholder: 'Email', class: "input-field", required: true  

    = f.password_field :password, placeholder: 'Password', class: "input-field", required: true

    = f.submit "Signup", class: "btn"